### ISSUE TITLE
Javascript error reporting is useless

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cwc/web-page-screensaver#2]
```
What steps will reproduce the problem?
1. Load a URL for a blog that has Flowplayer video content on the page

What is the expected output? What do you see instead?

You get a dialog error complaining about the javascript.  It asks if you want 
to continue running scripts on this page.  You can click yes or no, but either 
escapes out of the screensaver.

What version of the product are you using? On what operating system?

Windows 7

Please provide any additional information below.

Maybe you can disable dialog errors?
```

Original issue reported on code.google.com by `pab...@gmail.com` on 14 Jul 2011 at 8:25

**Comment by cwc** [comment]
With the changes to use the newest IE, this shouldn't be as much of a problem. If it does happen, it can be worked around in some cases by disabling 'Close on mouse movement' in settings, in order to close the dialogs.

**Comment by davidwestonuk** [comment]
Still not working with jira dashboards - please can you advise how to suppress these script errors
