### ISSUE TITLE
It doesn't use my default browser to render webpage

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cwc/web-page-screensaver#4]
```
Hi. Is there a way to make web-page-screensaver to use my default web browser 
(Chrome) instead of the web browser used by web-page-screensaver (it looks like 
it's running on IE)? 

That page that I am trying to use for screensaver uses WebGL and it doesn't 
work on IE. 
```

Original issue reported on code.google.com by `soichih` on 30 Jul 2012 at 10:29

**Comment by cwc** [comment]
IMO it's not feasible for the app to switch which browser is used for rendering based on the user's default browser. That said, I'm considering moving the app to [CefSharp](https://github.com/cefsharp/CefSharp), which is probably the best renderer available.
