### ISSUE TITLE
No way of showing content in a frame as to eliminate scrollbars

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cwc/web-page-screensaver#6]
```
It would be nice to have an option to display content in its own frame so that 
there are no scroll bars present during the screensaver.
```

Original issue reported on code.google.com by `j.elna...@googlemail.com` on 11 Feb 2013 at 12:05

**Comment by cwc** [comment]
IMO this burden is on the website's design. Sites that are designed for user interaction with content below the fold will display scrollbars. Sites designed for full window visualization won't display scrollbars.
