### ISSUE TITLE
Impossible to login

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cwc/web-page-screensaver#9]
```
What steps will reproduce the problem?
1. Trying to make this my screensaver: 
https://www.google.com/trends/hottrends/visualize?nrow=5&ncol=5

What is the expected output? What do you see instead?
Instead it displays the Google login screen, which I can't type on because that 
would exit the screensaver

What version of the product are you using? On what operating system?
Windows 8

Please provide any additional information below.

```

Original issue reported on code.google.com by `iansom...@gmail.com` on 12 Jun 2013 at 2:21

**Comment by cwc** [comment]
This is worked around by disabling the 'Close on mouse movement' option, starting the screen saver, and logging in to the site. The option can then be re-enabled, and the screen saver used as normal (at least, until the site invalidates the user's session).
